packages:
  - apps/*
  - packages/*

catalog:
  '@discordjs/collection': ^2.1.1
  '@discordjs/core': ^2.4.0
  '@discordjs/formatters': ^0.6.2
  '@discordjs/rest': ^2.6.0
  '@discordjs/util': ^1.2.0
  '@discordjs/ws': ^2.0.4
  '@electric-sql/pglite': ^0.3.15
  '@rspack/cli': ^1.7.5
  '@rspack/core': ^1.7.5
  '@types/pg': ^8.16.0
  bufferutil: ^4.1.0
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  node-loader: ^2.1.0
  pg: ^8.18.0
  yoctocolors: ^2.1.2
  zlib-sync: ^0.1.10

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - zlib-sync
