packages:
  - apps/*
  - packages/*

catalog:
  '@discordjs/collection': ^2.1.1
  '@discordjs/core': ^2.3.0
  '@discordjs/formatters': ^0.6.1
  '@discordjs/rest': ^2.6.0
  '@discordjs/util': ^1.1.1
  '@discordjs/ws': ^2.0.3
  '@rspack/cli': ^1.6.0
  '@rspack/core': ^1.6.0
  '@types/pg': ^8.15.6
  bufferutil: ^4.0.9
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  node-loader: ^2.1.0
  pg: ^8.16.3
  yoctocolors: ^2.1.2
  zlib-sync: ^0.1.10

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - zlib-sync
